In [1]:
import tensorflow as tf

In [2]:
#向量
a=tf.constant([1,2,3],name='a')
b=tf.constant([4,5,6],name='b')
c=a+b

In [5]:
with tf.Session() as sess:
    print('a+b=', sess.run(c))

a+b= [5 7 9]


In [13]:
#陣列
a=tf.constant([[1,2],[3,4]],name='a')
b=tf.constant([[1],[3]],name='b')
c=tf.matmul(a,b)

print('shape of a:', a.shape)
print('shape of b:', b.shape)
print('shape of c:', c.shape)

with tf.Session() as sess:
    print('a=\n', sess.run(a))
    print('b=\n', sess.run(b))
    print('c=\n', sess.run(c))

shape of a: (2, 2)
shape of b: (2, 1)
shape of c: (2, 1)
a=
 [[1 2]
 [3 4]]
b=
 [[1]
 [3]]
c=
 [[ 7]
 [15]]


In [22]:
#placeholder接收陣列張量
a=tf.placeholder(shape=(None,2),dtype=tf.int32, name='a')

with tf.Session() as sess:
    print('--代入[[1,2]]--')
    print('a=',sess.run(a,feed_dict={a:[[1,2]]}))
    print('--代入[[1,2],[3,4]]--')
    print('a=', sess.run(a,feed_dict={a:[[1,2],[3,4]]}))
    print('a=', sess.run(a,feed_dict={a:[[1,2],[3,4]]}))

--代入[[1,2]]--
a= [[1 2]]
--代入[[1,2],[3,4]]--
a= [[1 2]
 [3 4]]
a= [[1 2]
 [3 4]]


In [23]:
#Session之前，變數都必須初始化
a=tf.Variable(1,name='a')
b=tf.assign(a,a+1)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('第一次b=',sess.run(b))
    print('第二次b=',sess.run(b))

#離開Session之後，先前的紀錄就不見了
with tf.Session() as sess:
    print('--新session--')
    sess.run(tf.global_variables_initializer())
    print('第一次b=',sess.run(b))
    print('第二次b=',sess.run(b))
    print('第三次b=',sess.run(b))
    

第一次b= 2
第二次b= 3
--新session--
第一次b= 2
第二次b= 3
第三次b= 4


In [16]:
#Saver儲存變數

saver=tf.train.Saver()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('第一次b=',sess.run(b))
    print('第二次b=',sess.run(b))
    saver.save(sess,'model/model.ckpt')

第一次b= 2
第二次b= 3


In [17]:
#讀取

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #讀取剛剛儲存的值，繼續下去
    saver.restore(sess, save_path='model/model.ckpt')
    print(sess.run(b))
    print(sess.run(b))

INFO:tensorflow:Restoring parameters from model/model.ckpt
4
5
